#!/usr/bin/lua
require("luci.util")

cmdline = { "rrdtool", "graph" }
opts = { '/tmp/rrdimg/pool/exec-pool/graph-week.png', '-a', 'PNG', '-s', 'NOW-604800', '-w', '1000',
	'-t', 'pool: Pump current consumption (all week)', '-v', 'Amperes RMS',
	'DEF:1current_avg_raw=/mnt/sda1/pool/exec-pool/current-pump.rrd:value:AVERAGE',
	'CDEF:1current_avg=1current_avg_raw,0,+', 'CDEF:1current_nnl=1current_avg,UN,0,1current_avg,IF',
	'CDEF:1current_stk=1current_nnl', 'CDEF:1current_plot=1current_avg',
	'AREA:1current_plot#bfffbf' }
--	'GPRINT:1current_avg:AVERAGE:  Avg: %6.2lf', 'GPRINT:1current_avg:LAST:      Last: %6.2lf\l' }

for i, opt in ipairs(opts) do
	cmdline[#cmdline+1] = luci.util.shellquote(opt .. "")
end

outfile = io.open("/tmp/rrdtool-cmd", "w+")
outfile:write(table.concat(cmdline, " "))
outfile:close()
local rrdtool = io.popen(table.concat(cmdline, " "))
rrdtool:close()

local png = io.open("/tmp/rrdimg/pool/exec-pool/graph-week.png", "r")
if png then
	local content = png:read("*all")
	io.write("Content-Type: image/png\r\n")
	io.write("\r\n")
	io.write(content)
end
