#!/usr/bin/lua
require("luci.sys")
require("luci.jsonc")

function queryToTable(s)
	result = {};
	for match in (s..'&'):gmatch("(.-)"..'&') do
	local eq_from, eq_to = string.find(match, '=', 1)
	local val = string.sub(match, eq_from+1)
	val = val:gsub("%%3A", ":")
	result[string.sub(match, 1, eq_from-1)] = val
	end
	return result;
end

conf = io.open("/root/prj/devcron/config/timer.json", "w+")
local fields = queryToTable(luci.sys.getenv("QUERY_STRING"))
conf:write(luci.jsonc.stringify(fields))
conf:close()
io.write("Content-Type: text/html\r\n\r\n")
io.write('<html><head><meta http-equiv="refresh" content="0; URL=/"/></head><body>redirecting...<a href="http://pool.local">click here if necessary</a></body></html>')
-- io.write("\r\n")
-- print(luci.jsonc.stringify(luci.sys.getenv()))
-- print(luci.jsonc.stringify(fields))

